name: "antlr4"
version: "4.13.0"
description: "New Dart runtime for ANTLR4."
homepage: "https://github.com/antlr/antlr4"
license: "BSD-3-Clause"
dependencies: 
  logging: ^1.0.0
  collection: ^1.15.0
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.10
  benchmark_harness: ^2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
