version: 2.1

jobs:
  test_tool:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build ANTLR4 tool tests
          command: mvn -DskipTests -pl tool-testsuite -am install
      - run:
          name: test tool
          command: |
            cd tool-testsuite
            mvn test
            cd ..
  test_runtime:
    parameters:
      test-group:
        description: The section
        type: string
        default: ALL
      target:
        description: The target
        type: string
        default: java
    docker:
      - image: cimg/openjdk:11.0
        environment:
          MAVEN_OPTS: -Xmx512m
    parallelism: 4
    resource_class: large
    environment:
      TARGET: <<parameters.target>>
      GROUP: <<parameters.test-group>>
    steps:
      - checkout
      - run:
          name: Install <<parameters.target>> pre-requisites
          command: |
            set -euo pipefail
            f=".circleci/scripts/install-linux-<<parameters.target>>.sh"; ! [ -x "$f" ] || "$f"
      - run:
          name: Build ANTLR runtime tests
          command: mvn -DskipTests -pl runtime-testsuite -am install
      - run:
          name: Test <<parameters.target>> runtime
          command: |
            set -euo pipefail
            if [ "<<parameters.target>>" == "swift" ]
            then
              export PATH=$PATH:/usr/share/swift/usr/bin
            fi
            pushd runtime-testsuite
            mvn -Dtest=<<parameters.target>>.** test
            popd
      - run:
          name: Extra tests of <<parameters.target>> runtime
          command: |
            f=".circleci/scripts/run-tests-<<parameters.target>>.sh"; ! [ -x "$f" ] || "$f"

workflows:
  build:
    jobs:
      - test_tool
      - test_runtime:
          matrix:
            parameters:
              target: [ java, csharp, python2, python3, javascript, cpp, go, swift, php, dart ]
